// Code generated by Wire. DO NOT EDIT.

package di

import (
	"e-commerce/configs"
	"e-commerce/controllers"
	"e-commerce/repository"
	"e-commerce/services"
	"gorm.io/gorm"
)

// Container 定义应用程序的依赖注入容器
type Container struct {
	DB             *gorm.DB
	AuthController *controllers.AuthController
}

// provideDB 提供数据库实例
func provideDB(envFile string) *gorm.DB {
	return configs.ConnectDB(envFile).DB
}

// 生成的代码中还需要保持 Container 结构体和 provideDB 函数
func Initialize(envFile string) (*Container, error) {
	db := provideDB(envFile)
	userRepository := repository.NewGormUserRepository(db)
	authService := services.NewAuthService(userRepository)
	authController := controllers.NewAuthController(authService)
	container := &Container{
		DB:             db,
		AuthController: authController,
	}
	return container, nil
}